//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoPlanner.Usage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<StructureDefinitions>\r\n\t<StructureDefinition Name=\"Wall\" HasProtocolDefinition=\"" +
            "true\">\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPosition=\"Top\" Width" +
            "=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPositi" +
            "on=\"Top\" Width=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" V" +
            "erticalPosition=\"Top\" Width=\"48\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosit" +
            "ion=\"Left\" VerticalPosition=\"Center\" Width=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomin" +
            "o  x=\"0\" y=\"0\" Width=\"40\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"0\" yC" +
            "onstant=\"-1\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0" +
            "\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"" +
            "24\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"0\" yConstant=\"-2\"" +
            " xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMult" +
            "iplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"24\" Width=\"" +
            "8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"1\" yConstant=\"-2\" xPositionM" +
            "ultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/" +
            ">  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"48\" Height=\"" +
            "24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"0\" yConstant=\"-3\" xPositionMultiplier=\"" +
            "0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</R" +
            "ectangleDomino>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"48\" Width=\"32\" Height=\"24\">\r\n\t\t\t\t" +
            "<ProtocolDefinition xConstant=\"1\" yConstant=\"-3\" xPositionMultiplier=\"0\" yPositi" +
            "onMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDo" +
            "mino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDef" +
            "inition xConstant=\"0\" yConstant=\"-4\" xPositionMultiplier=\"0\" yPositionMultiplier" +
            "=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<R" +
            "ectangleDomino x=\"40\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xCo" +
            "nstant=\"1\" yConstant=\"-4\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" Width" +
            "Multiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t</PartDefiniti" +
            "on>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Center\" Wid" +
            "th=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"-40\" y=\"0\" Width=\"48\" Height=\"24\">\r" +
            "\n\t\t\t\t<ProtocolDefinition xConstant=\"1\" yConstant=\"-1\" xPositionMultiplier=\"2\" yP" +
            "ositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</Rectan" +
            "gleDomino>\r\n\t\t\t<RectangleDomino x=\"8\" y=\"0\" Width=\"32\" Height=\"24\">\r\n\t\t\t\t<Protoc" +
            "olDefinition xConstant=\"2\" yConstant=\"-1\" xPositionMultiplier=\"2\" yPositionMulti" +
            "plier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n" +
            "\t\t\t<RectangleDomino x=\"40\" y=\"0\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinitio" +
            "n xConstant=\"3\" yConstant=\"-1\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" " +
            "WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<Rectang" +
            "leDomino x=\"0\" y=\"24\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=" +
            "\"2\" yConstant=\"-2\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMultipl" +
            "ier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"" +
            "40\" y=\"24\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"3\" yConsta" +
            "nt=\"-2\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" Hei" +
            "ghtMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" W" +
            "idth=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-3\" xPo" +
            "sitionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultipli" +
            "er=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"48\" Width=\"32\" " +
            "Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"3\" yConstant=\"-3\" xPositionMult" +
            "iplier=\"2\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  " +
            "\r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Width=\"8\" Height=\"24\">" +
            "\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-4\" xPositionMultiplier=\"2\" y" +
            "PositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</Recta" +
            "ngleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<Prot" +
            "ocolDefinition xConstant=\"3\" yConstant=\"-4\" xPositionMultiplier=\"2\" yPositionMul" +
            "tiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>" +
            "\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosi" +
            "tion=\"Center\" Width=\"48\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"8\" y=\"0\" Width=\"40" +
            "\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-1\" xPositionMu" +
            "ltiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>" +
            "  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" Width=\"8\" Height=\"24" +
            "\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-2\" xPositionMultiplier=\"0\"" +
            " yPositionMultiplier=\"-4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</Rec" +
            "tangleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"24\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<Pr" +
            "otocolDefinition xConstant=\"3\" yConstant=\"-2\" xPositionMultiplier=\"0\" yPositionM" +
            "ultiplier=\"-4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomin" +
            "o>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefin" +
            "ition xConstant=\"2\" yConstant=\"-3\" xPositionMultiplier=\"0\" yPositionMultiplier=\"" +
            "-4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<Rec" +
            "tangleDomino x=\"0\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConst" +
            "ant=\"2\" yConstant=\"-4\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMul" +
            "tiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino" +
            " x=\"40\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"3\" yCo" +
            "nstant=\"-4\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"2\"" +
            " HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t</PartDefinition>\r\n\t\t<PartDe" +
            "finition HorizontalPosition=\"Left\" VerticalPosition=\"Bottom\" Width=\"80\" Height=\"" +
            "0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Bottom\" Wi" +
            "dth=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosi" +
            "tion=\"Bottom\" Width=\"48\" Height=\"0\"/>\r\n\t</StructureDefinition>\r\n\t<StructureDefin" +
            "ition Name=\"Wall, SDE Type Edge\" HasProtocolDefinition=\"true\">\r\n\t\t<PartDefinitio" +
            "n HorizontalPosition=\"Left\" VerticalPosition=\"Top\" Width=\"80\" Height=\"0\"/>\r\n\t\t<P" +
            "artDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Top\" Width=\"80\" Heig" +
            "ht=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Top\" Wi" +
            "dth=\"48\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPosit" +
            "ion=\"Center\" Width=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomino  x=\"24\" y=\"0\" Width=\"1" +
            "6\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"0\" yConstant=\"-1\" xPositionM" +
            "ultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/" +
            ">  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"24\" Height=\"4" +
            "8\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"0\" yConstant=\"-2\" xPositionMultiplier=\"0" +
            "\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</Re" +
            "ctangleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"24\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<P" +
            "rotocolDefinition xConstant=\"1\" yConstant=\"-2\" xPositionMultiplier=\"0\" yPosition" +
            "Multiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomi" +
            "no>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefi" +
            "nition xConstant=\"0\" yConstant=\"-3\" xPositionMultiplier=\"0\" yPositionMultiplier=" +
            "\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<Re" +
            "ctangleDomino x=\"48\" y=\"48\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xCo" +
            "nstant=\"1\" yConstant=\"-3\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" Width" +
            "Multiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDom" +
            "ino x=\"0\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"0\" y" +
            "Constant=\"-4\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"" +
            "0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y" +
            "=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"1\" yConstant=\"-" +
            "4\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMu" +
            "ltiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition " +
            "HorizontalPosition=\"Center\" VerticalPosition=\"Center\" Width=\"80\" Height=\"96\">\r\n\t" +
            "\t\t<RectangleDomino x=\"-40\" y=\"0\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinitio" +
            "n xConstant=\"1\" yConstant=\"-1\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" " +
            "WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<Rectang" +
            "leDomino x=\"8\" y=\"0\" Width=\"32\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=" +
            "\"2\" yConstant=\"-1\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMultipl" +
            "ier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"" +
            "40\" y=\"0\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"3\" yConsta" +
            "nt=\"-1\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" Hei" +
            "ghtMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" W" +
            "idth=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-2\" xPos" +
            "itionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplie" +
            "r=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"24\" Width=\"8\" He" +
            "ight=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"3\" yConstant=\"-2\" xPositionMultip" +
            "lier=\"2\" yPositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n" +
            "\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"48\" Height=\"24\">\r" +
            "\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-3\" xPositionMultiplier=\"2\" yP" +
            "ositionMultiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</Rectan" +
            "gleDomino>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"48\" Width=\"32\" Height=\"24\">\r\n\t\t\t\t<Prot" +
            "ocolDefinition xConstant=\"3\" yConstant=\"-3\" xPositionMultiplier=\"2\" yPositionMul" +
            "tiplier=\"-4\" WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>" +
            "\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefiniti" +
            "on xConstant=\"2\" yConstant=\"-4\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\"" +
            " WidthMultiplier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<Rectan" +
            "gleDomino x=\"40\" y=\"72\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstan" +
            "t=\"3\" yConstant=\"-4\" xPositionMultiplier=\"2\" yPositionMultiplier=\"-4\" WidthMulti" +
            "plier=\"0\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t</PartDefinition>\r\n" +
            "\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Center\" Width=\"48" +
            "\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"8\" y=\"0\" Width=\"16\" Height=\"24\">\r\n\t\t\t\t<Pr" +
            "otocolDefinition xConstant=\"2\" yConstant=\"-1\" xPositionMultiplier=\"0\" yPositionM" +
            "ultiplier=\"-4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomin" +
            "o>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefini" +
            "tion xConstant=\"2\" yConstant=\"-2\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-" +
            "4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<Rect" +
            "angleDomino x=\"24\" y=\"0\" Width=\"24\" Height=\"48\">\r\n\t\t\t\t<ProtocolDefinition xConst" +
            "ant=\"3\" yConstant=\"-2\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMul" +
            "tiplier=\"2\" HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino" +
            " x=\"0\" y=\"48\" Width=\"48\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yCo" +
            "nstant=\"-3\" xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"2\"" +
            " HeightMultiplier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"7" +
            "2\" Width=\"8\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"2\" yConstant=\"-4\" " +
            "xPositionMultiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"2\" HeightMulti" +
            "plier=\"4\"/>  \r\n\t\t\t</RectangleDomino>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"72\" Width=\"8" +
            "\" Height=\"24\">\r\n\t\t\t\t<ProtocolDefinition xConstant=\"3\" yConstant=\"-4\" xPositionMu" +
            "ltiplier=\"0\" yPositionMultiplier=\"-4\" WidthMultiplier=\"2\" HeightMultiplier=\"4\"/>" +
            "  \r\n\t\t\t</RectangleDomino>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosi" +
            "tion=\"Left\" VerticalPosition=\"Bottom\" Width=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition" +
            " HorizontalPosition=\"Center\" VerticalPosition=\"Bottom\" Width=\"80\" Height=\"0\"/>\r\n" +
            "\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Bottom\" Width=\"48" +
            "\" Height=\"0\"/>\r\n\t</StructureDefinition>\r\n\t<StructureDefinition Name=\"T-Wall\" Has" +
            "ProtocolDefinition=\"false\">\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" Vertica" +
            "lPosition=\"Top\" Width=\"0\" Height=\"56\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"C" +
            "enter\" VerticalPosition=\"Top\" Width=\"96\" Height=\"56\">\r\n\t\t\t<RectangleDomino x=\"0\"" +
            " y=\"0\" Width=\"48\" Height=\"8\"/>\r\n\t\t\t<RectangleDomino x=\"20\" y=\"8\" Width=\"8\" Heigh" +
            "t=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"32\" Width=\"48\" Height=\"8\"/>\r\n\t\t</PartDef" +
            "inition>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Top\" Wi" +
            "dth=\"0\" Height=\"56\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPosit" +
            "ion=\"Center\" Width=\"0\" Height=\"56\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Cent" +
            "er\" VerticalPosition=\"Center\" Width=\"96\" Height=\"56\">\r\n\t\t\t<RectangleDomino x=\"0\"" +
            " y=\"0\" Width=\"48\" Height=\"8\"/>\r\n\t\t\t<RectangleDomino x=\"20\" y=\"8\" Width=\"8\" Heigh" +
            "t=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"32\" Width=\"48\" Height=\"8\"/>\r\n\t\t\t<Rectang" +
            "leDomino x=\"68\" y=\"-16\" Width=\"8\" Height=\"48\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDef" +
            "inition HorizontalPosition=\"Right\" VerticalPosition=\"Center\" Width=\"0\" Height=\"5" +
            "6\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPosition=\"Bottom\" Widt" +
            "h=\"0\" Height=\"64\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosit" +
            "ion=\"Bottom\" Width=\"96\" Height=\"64\">\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"48\"" +
            " Height=\"8\"/>\r\n\t\t\t<RectangleDomino x=\"20\" y=\"8\" Width=\"8\" Height=\"48\"/>\r\n\t\t\t<Rec" +
            "tangleDomino x=\"48\" y=\"32\" Width=\"48\" Height=\"8\"/>\r\n\t\t\t<RectangleDomino x=\"48\" y" +
            "=\"40\" Width=\"48\" Height=\"8\"/>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"48\" Width=\"48\" Heig" +
            "ht=\"8\"/>\r\n\t\t\t<RectangleDomino x=\"48\" y=\"56\" Width=\"48\" Height=\"8\"/>\r\n\t\t\t<Rectang" +
            "leDomino x=\"68\" y=\"-16\" Width=\"8\" Height=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"56" +
            "\" Width=\"48\" Height=\"8\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosi" +
            "tion=\"Right\" VerticalPosition=\"Bottom\" Width=\"0\" Height=\"64\"/>\r\n\t</StructureDefi" +
            "nition>\r\n\t<StructureDefinition Name=\"Cube Side 1\" HasProtocolDefinition=\"false\">" +
            "\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPosition=\"Top\" Width=\"80\" " +
            "Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"To" +
            "p\" Width=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" Vertica" +
            "lPosition=\"Top\" Width=\"48\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"L" +
            "eft\" VerticalPosition=\"Center\" Width=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"4" +
            "8\" y=\"0\" Width=\"32\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"48\" He" +
            "ight=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" Width=\"8\" Height=\"24\"/>\r\n\t\t\t<Recta" +
            "ngleDomino x=\"40\" y=\"24\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"" +
            "48\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y =\"72\" Width=\"8\" Height" +
            "=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"40\" y =\"72\" Width=\"8\" Height=\"24\"/>\r\n\t\t</PartDef" +
            "inition>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Center" +
            "\" Width=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"48\" y=\"0\" Width=\"32\" Height=\"2" +
            "4\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDom" +
            "ino x=\"0\" y=\"48\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Widt" +
            "h=\"8\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"72\" Width=\"8\" Height=\"24\"/>\r\n" +
            "\t\t\t<RectangleDomino x=\"40\" y=\"24\" Width=\"48\" Height=\"24\"/>\r\n\t\t</PartDefinition>\r" +
            "\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Center\" Width=\"4" +
            "8\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<R" +
            "ectangleDomino x=\"40\" y=\"24\" Width=\"8\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" " +
            "y=\"48\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Width=\"8\" Heig" +
            "ht=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"40\" y=\"72\" Width=\"8\" Height=\"24\"/>\r\n\t\t</PartDe" +
            "finition>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPosition=\"Bottom\"" +
            " Width=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" Vertical" +
            "Position=\"Bottom\" Width=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=" +
            "\"Right\" VerticalPosition=\"Bottom\" Width=\"48\" Height=\"0\"/>\r\n\t</StructureDefinitio" +
            "n>\r\n\t<StructureDefinition Name=\"Cube Side 2\" HasProtocolDefinition=\"false\">\r\n\t\t<" +
            "PartDefinition HorizontalPosition=\"Left\" VerticalPosition=\"Top\" Width=\"80\" Heigh" +
            "t=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Top\" Wi" +
            "dth=\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosi" +
            "tion=\"Top\" Width=\"48\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" " +
            "VerticalPosition=\"Center\" Width=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"48\" y=" +
            "\"24\" Width=\"32\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Width=\"48\" Heigh" +
            "t=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"8\" Height=\"24\"/>\r\n\t\t\t<Rectangle" +
            "Domino x=\"40\" y=\"0\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" W" +
            "idth=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y =\"48\" Width=\"8\" Height=\"24\"" +
            "/>\r\n\t\t\t<RectangleDomino x=\"40\" y =\"48\" Width=\"8\" Height=\"24\"/>\r\n\t\t</PartDefiniti" +
            "on>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Center\" Wid" +
            "th=\"80\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"40\" y=\"0\" Width=\"48\" Height=\"24\"/>\r" +
            "\n\t\t\t<RectangleDomino x=\"48\" y=\"24\" Width=\"32\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino" +
            " x=\"0\" y=\"72\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" Width=\"" +
            "48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"8\" Height=\"24\"/>\r\n\t\t\t" +
            "<RectangleDomino x=\"40\" y=\"48\" Width=\"8\" Height=\"24\"/>\r\n\t\t</PartDefinition>\r\n\t\t<" +
            "PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Center\" Width=\"48\" H" +
            "eight=\"96\">\r\n\t\t\t<RectangleDomino x=\"0\" y=\"72\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<Rect" +
            "angleDomino x=\"-40\" y=\"0\" Width=\"48\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"40\" y" +
            "=\"0\" Width=\"8\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"24\" Width=\"48\" Height" +
            "=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"8\" Height=\"24\"/>\r\n\t\t\t<Rectangle" +
            "Domino x=\"40\" y=\"48\" Width=\"8\" Height=\"24\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefini" +
            "tion HorizontalPosition=\"Left\" VerticalPosition=\"Bottom\" Width=\"80\" Height=\"0\"/>" +
            "\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Bottom\" Width=" +
            "\"80\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition" +
            "=\"Bottom\" Width=\"48\" Height=\"0\"/>\r\n\t</StructureDefinition>\r\n\t<StructureDefinitio" +
            "n Name=\"Edge Wall by Linux5324\" HasProtocolDefinition=\"false\">\r\n\t\t<PartDefinitio" +
            "n HorizontalPosition=\"Left\" VerticalPosition=\"Top\" Width=\"28.284\" Height=\"0\"/>\r\n" +
            "\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Top\" Width=\"56.5" +
            "69\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=" +
            "\"Top\" Width=\"45.255\" Height=\"0\"/>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" V" +
            "erticalPosition=\"Center\" Width=\"28.284\" Height=\"96\">\r\n\t\t\t<RectangleDomino x=\"0\" " +
            "y=\"0\" Width=\"22.627\" Height=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48\" Width=\"16.9" +
            "71\" Height=\"24\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Ce" +
            "nter\" VerticalPosition=\"Center\" Width=\"56.568\" Height=\"96\">\r\n\t\t\t<RectangleDomino" +
            " x=\"0\" y=\"0\" Width=\"39.598\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"-11.313\" y=\"24" +
            "\" Width=\"22.627\" Height=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"11.314\" y=\"24\" Width=\"28." +
            "284\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"-28.284\" y=\"72\" Width=\"39.598\" Height" +
            "=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"11.314\" y=\"72\" Width=\"11.314\" Height=\"24\"/>\r\n\t\t\t" +
            "<RectangleDomino x=\"28.284\" y=\"48\" Width=\"16.971\" Height=\"24\"/>\r\n\t\t\t<RectangleDo" +
            "mino x=\"28.284\" y=\"72\" Width=\"39.598\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"45.2" +
            "55\" y=\"24\" Width=\"22.627\" Height=\"48\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition " +
            "HorizontalPosition=\"Right\" VerticalPosition=\"Center\" Width=\"45.255\" Height=\"96\">" +
            "\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0\" Width=\"39.598\" Height=\"24\"/>\r\n\t\t\t<RectangleDom" +
            "ino x=\"11.314\" y=\"24\" Width=\"28.284\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"11.31" +
            "4\" y=\"72\" Width=\"5.657\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"16.971\" y=\"48\" Wid" +
            "th=\"22.627\" Height=\"48\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosi" +
            "tion=\"Left\" VerticalPosition=\"Bottom\" Width=\"28.284\" Height=\"72\">\r\n\t\t\t<Rectangle" +
            "Domino x=\"0\" y=\"0\" Width=\"22.627\" Height=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"0\" y=\"48" +
            "\" Width=\"16.971\" Height=\"24\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition Horizonta" +
            "lPosition=\"Center\" VerticalPosition=\"Bottom\" Width=\"56.569\" Height=\"72\">\r\n\t\t\t<Re" +
            "ctangleDomino x=\"0\" y=\"0\" Width=\"39.598\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"-" +
            "11.313\" y=\"24\" Width=\"22.627\" Height=\"48\"/>\r\n\t\t\t<RectangleDomino x=\"11.314\" y=\"2" +
            "4\" Width=\"28.284\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"28.284\" y=\"48\" Width=\"16" +
            ".971\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"45.255\" y=\"24\" Width=\"22.627\" Height" +
            "=\"48\"/>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" Verti" +
            "calPosition=\"Bottom\" Width=\"45.255\" Height=\"72\">\r\n\t\t\t<RectangleDomino x=\"0\" y=\"0" +
            "\" Width=\"39.598\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"11.314\" y=\"24\" Width=\"28." +
            "284\" Height=\"24\"/>\r\n\t\t\t<RectangleDomino x=\"11.314\" y=\"48\" Width=\"33.941\" Height=" +
            "\"24\"/>\r\n\t\t</PartDefinition>\r\n\t</StructureDefinition>\r\n\t<StructureDefinition Name" +
            "=\"Diagonal Field\" HasProtocolDefinition=\"true\">\r\n\t\t<PartDefinition HorizontalPos" +
            "ition=\"Left\" VerticalPosition=\"Top\" Width=\"16\" Height=\"16\"/>\r\n\t\t<PartDefinition " +
            "HorizontalPosition=\"Center\" VerticalPosition=\"Top\" Width=\"32\" Height=\"16\">\r\n\t\t\t<" +
            "PathDomino>\r\n\t\t\t\t<Point x=\"-8\" y=\"4\"/>\r\n\t\t\t\t<Point x=\"-4\" y=\"0\"/>\r\n\t\t\t\t<Point x=" +
            "\"8\" y=\"12\"/>\r\n\t\t\t\t<Point x=\"4\" y=\"16\"/>\r\n\t\t\t\t<ProtocolDefinition xConstant=\"1\" x" +
            "xPositionMultiplier=\"4\" yxPositionMultiplier=\"1\"/>\r\n\t\t\t</PathDomino>\r\n\t\t</PartDe" +
            "finition>\r\n\t\t<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Top\" W" +
            "idth=\"8\" Height=\"16\">\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Point x=\"-8\" y=\"4\"/>\r\n\t\t\t\t<Point x=" +
            "\"-4\" y=\"0\"/>\r\n\t\t\t\t<Point x=\"8\" y=\"12\"/>\r\n\t\t\t\t<Point x=\"4\" y=\"16\"/>\r\n\t\t\t\t<Protoco" +
            "lDefinition xConstant=\"1\" xWidthMultiplier=\"4\" yWidthMultiplier=\"1\" />\r\n\t\t\t</Pat" +
            "hDomino>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" Verti" +
            "calPosition=\"Center\" Width=\"16\" Height=\"32\">\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Point x=\"0\" " +
            "y=\"-4\"/>\r\n\t\t\t\t<Point x=\"4\" y=\"-8\"/>\r\n\t\t\t\t<Point x=\"16\" y=\"4\"/>\r\n\t\t\t\t<Point x=\"12" +
            "\" y=\"8\"/>\r\n\t\t\t\t<ProtocolDefinition yyPositionMultiplier=\"1\"/> \r\n\t\t\t</PathDomino>" +
            "\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPos" +
            "ition=\"Center\" Width=\"32\" Height=\"32\">\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Point x=\"-8\" y=\"20" +
            "\"/>\r\n\t\t\t\t<Point x=\"-4\" y=\"16\"/>\r\n\t\t\t\t<Point x=\"8\" y=\"28\"/>\r\n\t\t\t\t<Point x=\"4\" y=\"" +
            "32\"/>\r\n\t\t\t\t<ProtocolDefinition xConstant=\"1\" yConstant=\"1\" xxPositionMultiplier=" +
            "\"4\" yxPositionMultiplier=\"1\" yyPositionMultiplier=\"1\"/>\r\n\t\t\t</PathDomino>\r\n\t\t\t<P" +
            "athDomino>\r\n\t\t\t\t<Point x=\"0\" y=\"12\"/>\r\n\t\t\t\t<Point x=\"4\" y=\"8\"/>\r\n\t\t\t\t<Point x=\"1" +
            "6\" y=\"20\"/>\r\n\t\t\t\t<Point x=\"12\" y=\"24\"/>\r\n\t\t\t\t<ProtocolDefinition yConstant=\"1\" x" +
            "Constant=\"2\" xxPositionMultiplier=\"4\" yxPositionMultiplier=\"1\" yyPositionMultipl" +
            "ier=\"1\"/>\r\n\t\t\t</PathDomino>\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Point x=\"8\" y=\"4\"/>\r\n\t\t\t\t<Poi" +
            "nt x=\"12\" y=\"0\"/>\r\n\t\t\t\t<Point x=\"24\" y=\"12\"/>\r\n\t\t\t\t<Point x=\"20\" y=\"16\"/>\r\n\t\t\t\t<" +
            "ProtocolDefinition yConstant=\"1\" xConstant=\"3\" xxPositionMultiplier=\"4\" yxPositi" +
            "onMultiplier=\"1\" yyPositionMultiplier=\"1\"/>\r\n\t\t\t</PathDomino>\r\n\t\t\t<PathDomino>\r\n" +
            "\t\t\t\t<Point x=\"16\" y=\"-4\"/>\r\n\t\t\t\t<Point x=\"20\" y=\"-8\"/>\r\n\t\t\t\t<Point x=\"32\" y=\"4\"/" +
            ">\r\n\t\t\t\t<Point x=\"28\" y=\"8\"/>\r\n\t\t\t\t<ProtocolDefinition yConstant=\"1\" xConstant=\"4" +
            "\" xxPositionMultiplier=\"4\" yxPositionMultiplier=\"1\" yyPositionMultiplier=\"1\"/>\r\n" +
            "\t\t\t</PathDomino>\r\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Rig" +
            "ht\" VerticalPosition=\"Center\" Width=\"8\" Height=\"32\">\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Poin" +
            "t x=\"-8\" y=\"20\"/>\r\n\t\t\t\t<Point x=\"-4\" y=\"16\"/>\r\n\t\t\t\t<Point x=\"8\" y=\"28\"/>\r\n\t\t\t\t<P" +
            "oint x=\"4\" y=\"32\"/>\r\n\t\t\t\t<ProtocolDefinition yConstant=\"1\" xConstant=\"1\" xWidthM" +
            "ultiplier=\"4\" yWidthMultiplier=\"1\" yyPositionMultiplier=\"1\"/>\r\n\t\t\t</PathDomino>\r" +
            "\n\t\t</PartDefinition>\r\n\t\t<PartDefinition HorizontalPosition=\"Left\" VerticalPositi" +
            "on=\"Bottom\" Width=\"16\" Height=\"8\">\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Point x=\"0\" y=\"-4\"/>\r\n" +
            "\t\t\t\t<Point x=\"4\" y=\"-8\"/>\r\n\t\t\t\t<Point x=\"16\" y=\"4\"/>\r\n\t\t\t\t<Point x=\"12\" y=\"8\"/>\r" +
            "\n\t\t\t\t<ProtocolDefinition yHeightMultiplier=\"1\"/>\r\n\t\t\t</PathDomino>\r\n\t\t</PartDefi" +
            "nition>\r\n\t\t<PartDefinition HorizontalPosition=\"Center\" VerticalPosition=\"Bottom\"" +
            " Width=\"32\" Height=\"8\">\r\n\t\t\t<PathDomino>\r\n\t\t\t\t<Point x=\"16\" y=\"-4\"/>\r\n\t\t\t\t<Point" +
            " x=\"20\" y=\"-8\"/>\r\n\t\t\t\t<Point x=\"32\" y=\"4\"/>\r\n\t\t\t\t<Point x=\"28\" y=\"8\"/>\r\n\t\t\t\t<Pro" +
            "tocolDefinition yConstant=\"1\" xConstant=\"4\" xxPositionMultiplier=\"4\" yxPositionM" +
            "ultiplier=\"1\" yHeightMultiplier=\"1\"/>\r\n\t\t\t</PathDomino>\r\n\t\t</PartDefinition>\r\n\t\t" +
            "<PartDefinition HorizontalPosition=\"Right\" VerticalPosition=\"Bottom\" Width=\"8\" H" +
            "eight=\"8\"/>\r\n\t</StructureDefinition>\r\n</StructureDefinitions>\r\n")]
        public string StructureTemplates {
            get {
                return ((string)(this["StructureTemplates"]));
            }
            set {
                this["StructureTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStartup {
            get {
                return ((bool)(this["FirstStartup"]));
            }
            set {
                this["FirstStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%appdata%/DominoPlanner/colors.DColor")]
        public string StandardColorArray {
            get {
                return ((string)(this["StandardColorArray"]));
            }
            set {
                this["StandardColorArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%user%/DominoPlanner")]
        public string StandardProjectPath {
            get {
                return ((string)(this["StandardProjectPath"]));
            }
            set {
                this["StandardProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%appdata%/DominoPlanner/OpenProjects.xml")]
        public string OpenProjectList {
            get {
                return ((string)(this["OpenProjectList"]));
            }
            set {
                this["OpenProjectList"] = value;
            }
        }
    }
}
