//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoPlanner.Usage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStartup {
            get {
                return ((bool)(this["FirstStartup"]));
            }
            set {
                this["FirstStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%appdata%/DominoPlanner/colors.DColor")]
        public string StandardColorArray {
            get {
                return ((string)(this["StandardColorArray"]));
            }
            set {
                this["StandardColorArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%user%/DominoPlanner")]
        public string StandardProjectPath {
            get {
                return ((string)(this["StandardProjectPath"]));
            }
            set {
                this["StandardProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%appdata%/DominoPlanner/OpenProjects.xml")]
        public string OpenProjectList {
            get {
                return ((string)(this["OpenProjectList"]));
            }
            set {
                this["OpenProjectList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DColor")]
        public string ColorExtension {
            get {
                return ((string)(this["ColorExtension"]));
            }
            set {
                this["ColorExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DObject")]
        public string ObjectExtension {
            get {
                return ((string)(this["ObjectExtension"]));
            }
            set {
                this["ObjectExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DProject")]
        public string ProjectExtension {
            get {
                return ((string)(this["ProjectExtension"]));
            }
            set {
                this["ProjectExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources/Structures.xml")]
        public string StructureTemplates {
            get {
                return ((string)(this["StructureTemplates"]));
            }
            set {
                this["StructureTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%localappdata%/DominoPlanner")]
        public string SharePath {
            get {
                return ((string)(this["SharePath"]));
            }
            set {
                this["SharePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProtocolVM_HasNoProperties {
            get {
                return ((bool)(this["ProtocolVM_HasNoProperties"]));
            }
            set {
                this["ProtocolVM_HasNoProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProtocolVM_HasShortProperties {
            get {
                return ((bool)(this["ProtocolVM_HasShortProperties"]));
            }
            set {
                this["ProtocolVM_HasShortProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProtocolVM_HasExtendedProperties {
            get {
                return ((bool)(this["ProtocolVM_HasExtendedProperties"]));
            }
            set {
                this["ProtocolVM_HasExtendedProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProtocolVM_UseBlocks {
            get {
                return ((bool)(this["ProtocolVM_UseBlocks"]));
            }
            set {
                this["ProtocolVM_UseBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ProtocolVM_StonesPerBlock {
            get {
                return ((int)(this["ProtocolVM_StonesPerBlock"]));
            }
            set {
                this["ProtocolVM_StonesPerBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int LiveBuildHelperVM_FontSize {
            get {
                return ((int)(this["LiveBuildHelperVM_FontSize"]));
            }
            set {
                this["LiveBuildHelperVM_FontSize"] = value;
            }
        }
    }
}
